### ISSUE TITLE
Stylelint doesn't catch mistyped background-image value

### ISSUE THREAD

**Issue by Volker-E** [wikimedia/stylelint-config-wikimedia#121]
That's probably an upstream issue, but 
```
.link-https {
	background-image: images/external-ltr.svg );
```

isn't caught locally.

**Comment by edg2s** [comment]
Are you in LESS mode? I imagine that uses a less strict parser than the CSS parser. If there's a bug in the CSS parser it will be postcss-safe-parser.

**Comment by edg2s** [comment]
It looks like stylelint doesn't do much syntax validation beyond that implemented specific rules. None of this causes parser errors:
```css
.foo {
  background: foo.jpg );
  display: hello?;
  water: wet;
  width: wide;
}
```

You get `property-no-unknown` for `water`, but that's not a specific rule, not a parser error.
