### ISSUE TITLE
Add `rule-empty-line-before`

### ISSUE THREAD

**Issue by Volker-E** [wikimedia/stylelint-config-wikimedia#76]
This missing feature has been an upsetting part so far to  – the chaotic variability of how we're applying with new lines before selectors across the board:
I propose that we require `always` except after comments and when nesting selectors in `media` and `supports` queries. Things like that should not be possible any more:

```less
.site__title {
	color: #222;
	font-family: system-ui, sans-serif;
}
.site__title a {
	color: inherit;
}
.site__title a:hover {
	// Test comment

	color: #000; 
}

@media only screen and ( max-width: 480px ) {

	.site__title {
		color: #444;
	}
}
```

**Expected outcome:**
```less
.site__title {
	color: #222;
	font-family: system-ui, sans-serif;
}

.site__title a {
	color: inherit;
}

.site__title a:hover {
	// Test comment
	color: #000; 
}

@media only screen and ( max-width: 480px ) {
	.site__title {
		color: #444;
	}
}
```
